name: Actions workflow

on:
  repository_dispatch:
    types: [build]

jobs:
    run-github-actions:
      runs-on: ubuntu-latest
      steps:
          - name: Dispatcher Client Payload
            run: echo ${{ github.event.client_payload.env }} 
          - name: List the files
            run: |
              pwd
              ls -a
              echo $GITHUB_SHA
              echo $GITHUB_REPOSITORY
              echo $GITHUB_WORKSPACE
              echo "${{ github.token }}"
          - name: Checkout
            uses: actions/checkout@v2.3.3
          - name: List files after checkout
            run: |
              pwd
              ls -a  
          - name: simple javascript action
            id: greet
            uses: actions/hello-world-javascript-action@master
            with:
              who-to-greet: Siva
          - name: Log Greeting Time
            run: echo "${{ steps.greet.outputs.time }}"  
