name: Docker container
on:
  push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:15.0.1-alpine3.10
    steps:
      - name: node version
        run: | 
          node -v
          cat /etc/os-release
        