name: download artifact

on:
  push:
   branches:
    - '**'

jobs:
  download-artifacts:
    name: Download artifacts
    runs-on: ubuntu-latest
    steps:
     - name: Get artifact id
       shell: bash
       run: |
         echo artifactId = $(curl -sL https://api.github.com/repos/bv-sivakp/github-actions-example/actions/artifacts | jq -r '.artifacts[0].id?') >> $GITHUB_ENV
     - name: Download artifacts
       shell: bash
       run: |
         curl --request GET \
          --url https://api.github.com/repos/bv-sivakp/github-actions-example/actions/artifacts/26805710/zip \
          --header 'authorization: token ${{ env.PERSONAL_ACCESS_TOKEN }}' \
          --header 'Accept: application/vnd.github.v3+json' \                   
         ll -a                         
