name: download artifact

on:
  push:
   branches:
    - '**'

jobs:
  download-artifacts:
    name: Download artifacts
    runs-on: ubuntu-latest
    steps:
     - name: Get artifact id
       run: |
         echo $(curl -sL https://api.github.com/repos/bv-sivakp/github-actions-example/actions/artifacts | jq -r '.artifacts[0].id?')
         echo ART_ID= curl -sL https://api.github.com/repos/bv-sivakp/github-actions-example/actions/artifacts | jq -r '.artifacts[0].id?' >> $GITHUB_ENV
         echo "action_state=yellow" >> $GITHUB_ENV
     - name: Download artifacts
       run: |
         echo $action_state
         curl -sL https://api.github.com/repos/bv-sivakp/github-actions-example/actions/artifacts/$ART_ID/zip
         ll -a
              
           
