name: download artifact

on:
  push:
   branches:
    - '**'

jobs:
  download-artifacts:
    name: Download artifacts
    runs-on: ubuntu-latest
    steps:
     - name: Get artifact id
       run: |
         echo artifactId = $(curl -sL https://api.github.com/repos/bv-sivakp/github-actions-example/actions/artifacts | jq -r '.artifacts[0].id?') >> $GITHUB_ENV
     - name: Download artifacts
       run: |
         curl -sL https://api.github.com/repos/bv-sivakp/github-actions-example/actions/artifacts/${{ env.artifactId }}/zip
         ll -a
              
           
