name: initiate workflow dispatch
on:
  push:
   branches:
    - '**'

jobs:
  invoke-workflow:
    name: invoke workflow
    runs-on: ubuntu-latest
    steps:
      - name: invoke workflow
        run: |
         run: |
          curl --request POST \
          --url https://api.github.com/repos/bv-sivakp/github-actions-example/actions/workflows/pipeline.yml/dispatches \
          --header 'authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}' \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'content-type: application/json' \
          --data '{
               "ref":"master",
               "inputs": {                  
                  "APPNAME": GITHUB-ACTIONS-EXAMPLE
               }
            }'
