name: Strategy
on: [push]

jobs:
 pipe-line:
   name: pipeline
   runs-on:  ubuntu-latest
   steps:
     - name: Echo
       run: |
         echo "pipeline job"
 test-matrix-strategy:
   name: testmatrixstrategy
   runs-on: ubuntu-latest    
   strategy:
       matrix:
         repo: [ repo-1, repo-2, repo-3 ]
         repo-tag: [ repo-1-tag, repo-2-tag, repo-3-tag ]         
       max-parallel: 1   
   steps:
       - name: Echo Inputs
         run: |
           echo "Repository ${{ matrix.repo }}"
           echo "Repository Tag ${{ matrix.repo-tag }}"
