name: Strategy
on: [push]

jobs:
 node-version:
   runs-on: ubuntu-latest
   steps:
       - name: Log node version
         run: node -v
       - uses: actions/checkout@v2
         with:
           node-version: 12
       - name: Log node specific version
         run: node -v
         