name: publish artifacts
on:
  push:
   branches:
    - '**'

jobs:
  publish-artifacts:
    name: publish artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
         fetch-depth: 0      
      - name: publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-file
          path: testfile.json
      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: test-file
      - name: Display structure of downloaded files
        run: ls -R
