name: shell commands

on:
  push:
    branches: '**'
  pull_request:
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: muliline script
        run: |
          node -v
          npm -v
      - name: Testing Directory changes1
        run: |
          mkdir testingdir && cd testingdir
      - name: Testing Directory changes2
        run: |
          pwd        
      - name: python Command
        run: |
          import platform
          print(platform.processor()) 
        shell: python
      - id: sets-a-secret
        run: |
          the_secret=$((RANDOM))
          echo "::add-mask::$the_secret"
          echo "::set-output name=secret-number::$the_secret"
      - run: |
          echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-number }}"
      - run: |
          # RUN_INFO={"GITHUB_RUN_NUMBER": $GITHUB_RUN_NUMBER, "URL": $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID }
          echo "GITHUB_SERVER_URL $GITHUB_SERVER_URL"
          echo "GITHUB_REPOSITORY $GITHUB_REPOSITORY"
          echo "GITHUB_RUN_ID $GITHUB_RUN_ID"
  run-windows-shell-command:
     runs-on: windows-latest
     needs: ["run-shell-command"]
     steps:
         - name: Directory Powershell
           run: Get-Location
         - name: Directory Bash
           run: pwd
           shell: bash  
